-- Supabase Postgres preparation schema.
-- This runs alongside the existing SQLite/Render flow. Do not drop existing SQLite data.

create table if not exists public.products (
  sku text primary key,
  description text,
  family_description text,
  category text,
  standard_cost numeric default 0,
  purchase_price numeric default 0,
  sale_price numeric default 0,
  weight numeric default 0,
  supplier text,
  pick_order numeric default 999999,
  units_per_carton numeric default 1,
  updated_at timestamptz default now()
);

create table if not exists public.sales_raw (
  id bigserial primary key,
  sale_date date,
  customer_no text,
  customer_name text,
  sku text,
  product_desc text,
  quantity numeric default 0,
  amount numeric default 0,
  cost numeric default 0,
  profit numeric default 0,
  supplier text,
  category text,
  return_units numeric default 0,
  purchase_units numeric default 0,
  agent text,
  updated_at timestamptz default now()
);

create index if not exists idx_sales_customer_date on public.sales_raw (customer_no, sale_date);
create index if not exists idx_sales_sku_date on public.sales_raw (sku, sale_date);
create index if not exists idx_sales_category_date on public.sales_raw (category, sale_date);

create table if not exists public.sales_recommendations (
  id bigint generated by default as identity primary key,
  text text not null,
  active integer not null default 1,
  updated_at timestamptz default now()
);

create table if not exists public.customer_call_profiles (
  customer_no text primary key,
  customer_name text,
  phone text,
  address text,
  call_days text,
  source text default 'calls',
  updated_at timestamptz default now()
);

create table if not exists public.customer_calls (
  id bigint generated by default as identity primary key,
  call_date date,
  customer_no text,
  customer_name text,
  status text,
  call_again_time text,
  whatsapp_sent_at timestamptz,
  manual_order_id bigint,
  notes text,
  updated_at timestamptz default now()
);

create unique index if not exists idx_customer_calls_day_customer
  on public.customer_calls (call_date, customer_no);

create table if not exists public.customer_orders (
  id bigint generated by default as identity primary key,
  order_date date,
  customer_no text,
  customer_name text,
  status text,
  notes text,
  estimated_total numeric default 0,
  estimated_profit numeric default 0,
  picked_by text,
  picked_at timestamptz,
  invoice_printed integer not null default 0,
  shipped_at timestamptz,
  process_hidden integer not null default 0,
  client_order_key text unique,
  updated_at timestamptz default now()
);

create index if not exists idx_customer_orders_status on public.customer_orders (status, process_hidden);
create index if not exists idx_customer_orders_customer on public.customer_orders (customer_no, order_date);

create table if not exists public.customer_order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.customer_orders(id) on delete cascade,
  sku text,
  product_desc text,
  quantity numeric default 0,
  picked_quantity numeric default 0,
  note text,
  item_status text not null default 'pending',
  substitute_product_id text,
  action_sequence bigint,
  entry_sequence bigint,
  is_carton integer not null default 0,
  units_per_carton numeric default 1,
  shortage_dismissed integer not null default 0,
  estimated_price numeric default 0,
  estimated_profit numeric default 0
);

create index if not exists idx_order_items_order on public.customer_order_items (order_id);
create index if not exists idx_order_items_status on public.customer_order_items (order_id, item_status);

-- Enable RLS only when the final app auth model is ready.
-- alter table public.products enable row level security;
-- alter table public.sales_raw enable row level security;
-- alter table public.customer_orders enable row level security;
-- alter table public.customer_order_items enable row level security;
-- alter table public.customer_calls enable row level security;
